### PR TITLE
Fix building on Windows

### PR DESCRIPTION
**Pull request by isaacbrodsky**
@dfellis 

A few changes here:
* Windows doesn't have libm, so it won't be linked if not found.
* MSVC doesn't permit zero length arrays, which were sometimes used in the tests. These have been replaced with `NULL` since they shouldn't be dereferenced.
* Fixed an issue in testH3IndexFat.c where the stack would get corrupted.
* Used Powershell on Windows. 

And one more unrelated change, which was some of the miscapps had invalid H3 indexes in their comments, has been fixed.

Edit: See also https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/ about CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS.

### CODE REVIEW

**Comment by dfellis** [comment]
Wow, my comment about Windows in that other PR was a joke. :)

Not home at the moment, but will take a look at this on a Windows VM when I'm back.

**Comment by dfellis** [comment]
Took all night to get the community edition of VisualStudio downloaded and installed on my VM. It doesn't quite work. :(

```
"C:\Users\damocles\oss\h3\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj" (default target) (3) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'lib\Debug\h3.1.lib' [C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj]
```

```
PS C:\Users\damocles\oss\h3> cd .\lib
PS C:\Users\damocles\oss\h3\lib> ls


    Directory: C:\Users\damocles\oss\h3\lib


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         1/15/2018   7:55 AM            Debug


PS C:\Users\damocles\oss\h3\lib> cd .\Debug
PS C:\Users\damocles\oss\h3\lib\Debug> ls


    Directory: C:\Users\damocles\oss\h3\lib\Debug


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---         1/15/2018   7:55 AM     112640 h3.1.dll
-a---         1/15/2018   7:55 AM     342160 h3.1.ilk
-a---         1/15/2018   7:55 AM     675840 h3.1.pdb


PS C:\Users\damocles\oss\h3\lib\Debug>
```

VisualStudio's `msbuild` command is generating a `.dll` file instead of a `.lib` file. The tests hard-link the library, so I presume there's some windows-specific configuration in CMake to have it generate static libraries. I'll read up more about it, but I'm back to work today so I can't spend as much time on it as I'd like.

**Comment by dfellis** [comment]
Actually, there's a *lot* wrong with building it on Windows, beyond the lack of a static library file.

```
cl : Command line warning D9002: ignoring unknown option '-g' [C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj]
  benchmarkH3Api.c
cl : Command line warning D9002: ignoring unknown option '-O0' [C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj]
cl : Command line warning D9002: ignoring unknown option '-fno-inline' [C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj
]
cl : Command line warning D9002: ignoring unknown option '-fno-eliminate-unused-debug-types' [C:\Users\damocles\oss\h3\
benchmarkH3Api.vcxproj]
cl : Command line warning D9002: ignoring unknown option '--coverage' [C:\Users\damocles\oss\h3\benchmarkH3Api.vcxproj]
```

@isaacbrodsky how did you get it to compile on Windows? Those steps probably deserve to be in the README, or a special `WINDOWS_DEVELOPERS.txt` file.

**Comment by isaacbrodsky** [comment]
Thanks for trying the build @dfellis. Here are the steps I followed:

```
mkdir build
cd build
cmake -DBUILD_STATIC=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ..
msbuild ALL_BUILD.vcxproj
```

This gives me 999 warnings and 0 errors. I did not fix the compiler warnings, having incorrect compiler flags on the command line isn't a good idea, but appears to be harmless. (Could change CMakeLists.txt to not set those options if WIN32.) At this point, I can use the filter apps (`bin\Debug\...`) and I can run the tests (`msbuiild RUN_TESTS.vcxproj`)

I then built the H3 DLL (`h3.1.dll`) separately:
```
cmake -DBUILD_STATIC=OFF -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ..
msbuild h3.1.vcxproj
```

The reason for building twice like this seems to be related to the H3 DLL not correctly exporting its symbols. If these steps work for you I'll add them to docs.

**Pull request merged**
