### PR TITLE
Add H3-Pandas to bindings

### PR DESCRIPTION
**Pull request by DahnJ**
As [discussed on Slack](https://h3-core.slack.com/archives/CPRTBDDQU/p1624876968023600?thread_ts=1622587058.011900&cid=CPRTBDDQU), I'm adding [H3-Pandas](https://github.com/DahnJ/H3-Pandas) to the bindings.

### CODE REVIEW

**Review by dfellis — APPROVED** [review]

**Review by isaacbrodsky — APPROVED** [review]

**Comment by DahnJ** [comment]
I have just noticed that the [bindings page](https://h3geo.org/docs/community/bindings#python) does not include H3-Pandas yet. Is there any more action required from my side?

**Comment by isaacbrodsky** [comment]
> I have just noticed that the [bindings page](https://h3geo.org/docs/community/bindings#python) does not include H3-Pandas yet. Is there any more action required from my side?

Sorry, no action on your part. I'll get it updated.

**Comment by isaacbrodsky** [comment]
It should be live! Sorry again for the delay - we should automate the website process more.

**Comment by DahnJ** [comment]
> It should be live! Sorry again for the delay - we should automate the website process more.

No worries, thanks for the quick reply!

**Pull request merged**
