### PR TITLE
drop "Cells" from a few function names

### PR DESCRIPTION
**Pull request by ajfriend**
Rename functions according to changes here: https://github.com/uber/h3/pull/441

### CODE REVIEW

**Review by dfellis — CHANGES_REQUESTED** [review]
This is making the API less consistent.

**Comment by ajfriend** [comment]
For reference, this discussion is currently continuing in https://github.com/uber/h3/pull/441

**Comment by ajfriend** [comment]
Moving this conversation to https://github.com/uber/h3/issues/451

**Comment by ajfriend** [comment]
Closing as discussed in #451

**Pull request closed without merging**
