### PR TITLE
Remove H3IndexFat from h3ToComponents app

### PR DESCRIPTION
**Pull request by dfellis**
This one was pretty simple, so I did it over lunch. :)

There are no tests for the apps (yet?) so I tested it by just exhaustively executing all paths in the application (therefore just two kinds of H3 indexes in normal and verbose mode ;) ).

```
damocles@Talyn:~/oss/h3(slim-components)$ ./bin/h3ToComponents
811fbffffffffff
1:1:15:6
149283080dcbffff
2:4:9:20:060401562
^C
damocles@Talyn:~/oss/h3(slim-components)$ ./bin/h3ToComponents --verbose
811fbffffffffff
╔════════════╗
║ H3Index    ║ 811fbffffffffff
╠════════════╣
║ Mode       ║ Hexagon (1)
║ Resolution ║ 1
║ Base Cell  ║ 15
║  1 Child   ║ 6
╚════════════╝

149283080dcbffff
╔════════════╗
║ H3Index    ║ 149283080dcbffff
╠════════════╣
║ Mode       ║ Unidirectional Edge (2)
║ Resolution ║ 9
║ Edge       ║ 4
║ Base Cell  ║ 20
║  1 Child   ║ 0
║  2 Child   ║ 6
║  3 Child   ║ 0
║  4 Child   ║ 4
║  5 Child   ║ 0
║  6 Child   ║ 1
║  7 Child   ║ 5
║  8 Child   ║ 6
║  9 Child   ║ 2
╚════════════╝

^C
damocles@Talyn:~/oss/h3(slim-components)$
```

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
It seemed that if there was any reason to keep the struct representation of H3Index, that h3ToComponents was it. I'm also OK with just entirely removing the struct.

**Comment by dfellis** [comment]
awesome

**Comment by dfellis** [comment]
Also, I don't have permission to merge any changes (that's up to you guys, now) so you'll have to land your own diff as well as mine @isaacbrodsky :)

**Comment by isaacbrodsky** [comment]
@dfellis It's just taking me a little while to get to merging things this week. :)

**Pull request merged**
