### PR TITLE
Set v4 as a released version on the website

### PR DESCRIPTION
**Pull request by isaacbrodsky**
Depends on #633.

### CODE REVIEW

**Review by nrabinowitz — APPROVED** [review]

**Comment by dfellis** [comment]
I presume this also depends on the various bindings releasing v4.0.0?

**Comment by isaacbrodsky** [comment]
> I presume this also depends on the various bindings releasing v4.0.0?

I think so? Otherwise most of the code samples it would direct users to will not be correct.

**Comment by dfellis** [comment]
> > I presume this also depends on the various bindings releasing v4.0.0?
> 
> I think so? Otherwise most of the code samples it would direct users to will not be correct.

It wasn't explicitly called out, so I wasn't sure if I :heavy_check_mark:'ed this PR that it would immediately go out when that's probably not the right thing to do, yet.

**Review by dfellis — APPROVED** [review]

**Review by ajfriend — APPROVED** [review]

**Comment by isaacbrodsky** [comment]
> > > I presume this also depends on the various bindings releasing v4.0.0?
> > 
> > 
> > I think so? Otherwise most of the code samples it would direct users to will not be correct.
> 
> It wasn't explicitly called out, so I wasn't sure if I ✔️'ed this PR that it would immediately go out when that's probably not the right thing to do, yet.

Yes, the idea is to merge #633 first on August 16, tag & release uber/h3 v4.0.0, update & release binding updates, and then merge this PR. (Releasing binding updates and this PR might be parallelized)

**Pull request merged**
