### PR TITLE
Update bindings.md

### PR DESCRIPTION
**Pull request by michaelbrichko**

### CODE REVIEW

**Comment by dfellis** [comment]
@michaelbrichko after your comment, we discussed the situation and this PR: https://github.com/uber/h3/pull/538 should prevent that sort of mixup again in the future, so this one *should* be unnecessary once that one's deployed.

**Comment by michaelbrichko** [comment]
ok

**Comment by michaelbrichko** [comment]
By unnecessary you mean that 4.x will become default very soon ? At the moment it's default on main page (https://h3geo.org/) but if you go to bindings tab, it's 3.x

**Comment by dfellis** [comment]
> By unnecessary you mean that 4.x will become default very soon ? At the moment it's default on main page (https://h3geo.org/) but if you go to bindings tab, it's 3.x

No, sorry, the other PR I linked should make it clear; we're just making the 3.x "community" pages a symlink to the 4.x ones, since they're identical.

4.0 has more work to go (and most of us no longer work for Uber, so this is much more of a volunteer project now in between our regular work duties).

**Comment by isaacbrodsky** [comment]
I think this is no longer needed with #538 - please let me know if not the case.

**Pull request closed without merging**
