### PR TITLE
Docusaurus site math rendering

### PR DESCRIPTION
**Pull request by ajfriend**
I was hoping to use some math in #529, but I'm having trouble figuring out what changes I need to make in Docusaurus to get it to render math without error.

I was following the instructions here: https://docusaurus.io/docs/markdown-features/math-equations

When I run locally, I'm currently seeing an error like:

```
❯ yarn start
yarn run v1.22.11
$ docusaurus start

   ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                    │
   │                                    Update available 2.0.0-beta.0 → 2.0.0-beta.9                                    │
   │                                                                                                                    │
   │                 To upgrade Docusaurus packages with the latest version, run the following command:                 │
   │   yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest @docusaurus/theme-live-codeblock@latest   │
   │                                                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Starting the development server...

A validation error occured.
The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.

Error: "stylesheets[0]" does not match any of the allowed types

    at Object.validateConfig (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/server/configValidation.js:118:15)
    at Object.loadConfig [as default] (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/server/config.js:18:31)
    at loadContext (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/server/index.js:38:47)
    at Object.load (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/server/index.js:90:27)
    at loadSite (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/commands/start.js:37:25)
    at start (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/lib/commands/start.js:44:25)
    at /Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/bin/docusaurus.js:94:5
    at Command.<anonymous> (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/bin/docusaurus.js:201:25)
    at Command.listener [as _actionHandler] (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/node_modules/commander/index.js:882:12)
    at Command.parse (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/node_modules/commander/index.js:717:10)
    at run (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/bin/docusaurus.js:319:7)
    at Object.<anonymous> (/Users/ajfriend/work/h3/website/node_modules/@docusaurus/core/bin/docusaurus.js:326:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### CODE REVIEW

**Comment by pfw** [comment]
This works ok with the upgrade to beta9 of docusaurus.

Screen Shot 2021-11-18 at 10 19 40 pm

**Comment by ajfriend** [comment]
So I think I've made progress with the docusaurus version bump, since things work for me locally. Thanks @pfw!

But now I'm seeing this issue with Github Actions, and I can't figure out why the node version isn't being upgraded:

```
Run yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error @docusaurus/core@2.0.0-beta.9: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.7"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.
Error: Process completed with exit code 1.
```

**Comment by pfw** [comment]
I think on this one it's running a different actions workflow - github/workflows/test-website.yml which is still at actions/setup-node@v1. Github Actions is better than having to have an external site doing these but I get lost in all the options and the delay between making changes and something happening - it would be better if there was an interactive way to validate some of the things.

**Comment by pfw** [comment]
I'm not an expert on these but had alerts on for the repo and feel the pain!

**Comment by pfw** [comment]
Victory!

**Comment by ajfriend** [comment]
I was confused that I wasn't seeing errors locally, but was seeing them in the GitHub Actions, but I guess that's the difference between `yarn start` and `yarn build`. I updated the `website/README.md` accordingly.

**Review by isaacbrodsky — APPROVED** [review]

**Pull request merged**
