### PR TITLE
Add DuckDB, Sqlite3 bindings

### PR DESCRIPTION
**Pull request by isaacbrodsky**

### CODE REVIEW

**Comment by ajfriend** [comment]
Awesome! Super excited for the DuckDB bindings!

Also, it looks like you're having the same build issues as i was having in #617 . Something must have changed with the Windows containers?

**Comment by isaacbrodsky** [comment]
> Awesome! Super excited for the DuckDB bindings!
> 
> Also, it looks like you're having the same build issues as i was having in #617 . Something must have changed with the Windows containers?

Yes, it appears the docs build has failed. https://github.com/uber/h3/pull/617#issuecomment-1173098112 Perhaps some graphviz/dot/doxygen update happened or a component was removed. I think we can simply disable building docs in the Windows CI, or try something like https://github.com/marketplace/actions/install-graphviz

**Review by nrabinowitz — APPROVED** [review]
!!

**Review by dfellis — APPROVED** [review]
:100:

**Pull request merged**
